"""Add wallet table

Revision ID: 4e8a059dac47
Revises: 7a5993b11637
Create Date: 2025-07-03 03:15:21.710916

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e8a059dac47"
down_revision: Union[str, None] = "7a5993b11637"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DEPOSIT",
                "WITHDRAWAL",
                "TRANSFER",
                "BONUS",
                "FEE",
                "ADJUSTMENT",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum("IN", "OUT", "INTERNAL", name="transactiondirection"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="transactionstatus",
            ),
            nullable=False,
        ),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("fee", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("related_user_id", sa.Integer(), nullable=True),
        sa.Column("reference_id", sa.String(length=100), nullable=True),
        sa.Column("tx_hash", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transaction_metadata", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["related_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tx_reference", "transactions", ["reference_id"], unique=False)
    op.create_index(
        "idx_tx_status_type", "transactions", ["status", "type"], unique=False
    )
    op.create_index(
        "idx_tx_user_created", "transactions", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_reference_id"),
        "transactions",
        ["reference_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_transactions_related_user_id"),
        "transactions",
        ["related_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_status"), "transactions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_tx_hash"), "transactions", ["tx_hash"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_type"), "transactions", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.create_table(
        "wallets",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("hex_address", sa.String(length=42), nullable=False),
        sa.Column("encrypted_private_key", sa.Text(), nullable=False),
        sa.Column("encryption_salt", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_monitored", sa.Boolean(), nullable=False),
        sa.Column("wallet_metadata", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hex_address"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_wallet_address_active", "wallets", ["address", "is_active"], unique=False
    )
    op.create_index(
        "idx_wallet_user_active", "wallets", ["user_id", "is_active"], unique=False
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=True)
    op.create_index(op.f("ix_wallets_id"), "wallets", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_index("idx_wallet_user_active", table_name="wallets")
    op.drop_index("idx_wallet_address_active", table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_tx_hash"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_related_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_reference_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index("idx_tx_user_created", table_name="transactions")
    op.drop_index("idx_tx_status_type", table_name="transactions")
    op.drop_index("idx_tx_reference", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
