"""add_collection_address_to_hd_wallet_masters

Revision ID: 93b2e4126195
Revises: ca0829d8a731
Create Date: 2025-07-08 19:41:13.561214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b2e4126195'
down_revision: Union[str, None] = 'ca0829d8a731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite의 제한사항으로 인해 nullable=True로 추가 (애플리케이션 레벨에서 검증)
    op.add_column('hd_wallet_masters', sa.Column('collection_address', sa.String(length=42), nullable=True, comment='마스터 수집 주소'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hd_wallet_masters', 'collection_address')
    # ### end Alembic commands ###
