"""add_transaction_analytics_tables

Revision ID: e78898c0e488
Revises: 4c2b2dfd8953
Create Date: 2025-07-03 05:58:55.665812

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e78898c0e488"
down_revision: Union[str, None] = "4c2b2dfd8953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "systemalerts",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("alert_data", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_system_alert_active",
        "systemalerts",
        ["is_active", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_system_alert_level", "systemalerts", ["level", "is_resolved"], unique=False
    )
    op.create_index(
        op.f("ix_systemalerts_alert_type"), "systemalerts", ["alert_type"], unique=False
    )
    op.create_index(op.f("ix_systemalerts_id"), "systemalerts", ["id"], unique=False)
    op.create_index(
        op.f("ix_systemalerts_is_active"), "systemalerts", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_systemalerts_is_resolved"),
        "systemalerts",
        ["is_resolved"],
        unique=False,
    )
    op.create_index(
        op.f("ix_systemalerts_level"), "systemalerts", ["level"], unique=False
    )
    op.create_table(
        "transactionsummarys",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("trx_deposits_count", sa.Integer(), nullable=False),
        sa.Column(
            "trx_deposits_amount", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("trx_withdrawals_count", sa.Integer(), nullable=False),
        sa.Column(
            "trx_withdrawals_amount", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("usdt_deposits_count", sa.Integer(), nullable=False),
        sa.Column(
            "usdt_deposits_amount", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("usdt_withdrawals_count", sa.Integer(), nullable=False),
        sa.Column(
            "usdt_withdrawals_amount", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("total_transactions", sa.Integer(), nullable=False),
        sa.Column(
            "total_volume_usd", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("total_fees_trx", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("total_fees_usdt", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_summary_period_type",
        "transactionsummarys",
        ["period_type", "period_start"],
        unique=False,
    )
    op.create_index(
        "idx_summary_user_period",
        "transactionsummarys",
        ["user_id", "period_type", "period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionsummarys_id"), "transactionsummarys", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_transactionsummarys_period_end"),
        "transactionsummarys",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionsummarys_period_start"),
        "transactionsummarys",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionsummarys_user_id"),
        "transactionsummarys",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "transactionalerts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("alert_data", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alert_level_resolved",
        "transactionalerts",
        ["level", "is_resolved"],
        unique=False,
    )
    op.create_index(
        "idx_alert_type_created",
        "transactionalerts",
        ["alert_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_alert_user_created",
        "transactionalerts",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionalerts_alert_type"),
        "transactionalerts",
        ["alert_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionalerts_id"), "transactionalerts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_transactionalerts_is_resolved"),
        "transactionalerts",
        ["is_resolved"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionalerts_level"), "transactionalerts", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_transactionalerts_transaction_id"),
        "transactionalerts",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionalerts_user_id"),
        "transactionalerts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactionalerts_user_id"), table_name="transactionalerts")
    op.drop_index(
        op.f("ix_transactionalerts_transaction_id"), table_name="transactionalerts"
    )
    op.drop_index(op.f("ix_transactionalerts_level"), table_name="transactionalerts")
    op.drop_index(
        op.f("ix_transactionalerts_is_resolved"), table_name="transactionalerts"
    )
    op.drop_index(op.f("ix_transactionalerts_id"), table_name="transactionalerts")
    op.drop_index(
        op.f("ix_transactionalerts_alert_type"), table_name="transactionalerts"
    )
    op.drop_index("idx_alert_user_created", table_name="transactionalerts")
    op.drop_index("idx_alert_type_created", table_name="transactionalerts")
    op.drop_index("idx_alert_level_resolved", table_name="transactionalerts")
    op.drop_table("transactionalerts")
    op.drop_index(
        op.f("ix_transactionsummarys_user_id"), table_name="transactionsummarys"
    )
    op.drop_index(
        op.f("ix_transactionsummarys_period_start"), table_name="transactionsummarys"
    )
    op.drop_index(
        op.f("ix_transactionsummarys_period_end"), table_name="transactionsummarys"
    )
    op.drop_index(op.f("ix_transactionsummarys_id"), table_name="transactionsummarys")
    op.drop_index("idx_summary_user_period", table_name="transactionsummarys")
    op.drop_index("idx_summary_period_type", table_name="transactionsummarys")
    op.drop_table("transactionsummarys")
    op.drop_index(op.f("ix_systemalerts_level"), table_name="systemalerts")
    op.drop_index(op.f("ix_systemalerts_is_resolved"), table_name="systemalerts")
    op.drop_index(op.f("ix_systemalerts_is_active"), table_name="systemalerts")
    op.drop_index(op.f("ix_systemalerts_id"), table_name="systemalerts")
    op.drop_index(op.f("ix_systemalerts_alert_type"), table_name="systemalerts")
    op.drop_index("idx_system_alert_level", table_name="systemalerts")
    op.drop_index("idx_system_alert_active", table_name="systemalerts")
    op.drop_table("systemalerts")
    # ### end Alembic commands ###
