# DantaroWalletPro 코드 품질 설정

# pre-commit 설정
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        args: [--line-length=88]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--max-line-length=88, --extend-ignore=E203]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-requests]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-ll", "-s", "B101"]

# 커스텀 훅: 코드 메트릭 검사
-   repo: local
    hooks:
    -   id: refactoring-check
        name: DantaroWalletPro 리팩토링 검사
        entry: python /Users/danielkwon/DantaroWalletPro/DantaroWalletPro/dantarowallet/scripts/refactoring_monitor.py
        language: system
        pass_filenames: false
        always_run: true

# 커스텀 훅: 품질 검사
-   repo: local
    hooks:
    -   id: quality-check
        name: DantaroWalletPro 코드 품질 검사
        entry: python /Users/danielkwon/DantaroWalletPro/DantaroWalletPro/dantarowallet/scripts/pre_commit_check.py
        language: system
        pass_filenames: false
        always_run: true
