#!/bin/bash

echo "=== TRON 테스트넷 TRX 받기 가이드 ==="
echo ""
echo "🎯 목표 주소: TZ8nMgTR7t8Wqk3tTHTbDtaMkifcZ46wWL"
echo ""
echo "🌐 Faucet 사이트들:"
echo "1. https://nileex.io/ (주요)"
echo "2. https://www.trongrid.io/faucet (공식)"
echo "3. https://faucet.shasta.trongrid.io/ (Shasta 테스트넷)"
echo ""
echo "📝 받기 방법:"
echo "1. 위 사이트 중 하나 접속"
echo "2. 주소 입력: TZ8nMgTR7t8Wqk3tTHTbDtaMkifcZ46wWL"
echo "3. 'Get TRX' 또는 'Request' 버튼 클릭"
echo "4. reCAPTCHA 완료"
echo "5. 1-5분 기다리기"
echo ""
echo "💰 받을 수 있는 양: 보통 10,000 TRX"
echo ""
echo "✅ 받은 후 확인:"
echo "python3 check_balance.py > balance_result.log 2>&1 && cat balance_result.log"
echo ""
echo "🚀 TRX가 확인되면 Sweep 테스트 실행:"
echo "python3 test_tron_transactions.py > sweep_test_final.log 2>&1 && cat sweep_test_final.log"
