# 에너지 API 시나리오 설정
energy_providers:
  tronnrg:
    name: "TronNRG"
    base_price: 45.0  # TRX per 1M energy
    price_volatility: 0.15  # 15% 변동성
    availability: 0.95  # 95% 가용성
    response_time_ms: [100, 500]
    daily_capacity: 1000000000  # 10억 에너지
    
  energytron:
    name: "EnergyTRON"
    base_price: 42.0
    price_volatility: 0.20  # 20% 변동성
    availability: 0.90  # 90% 가용성
    response_time_ms: [150, 800]
    daily_capacity: 800000000  # 8억 에너지

# 가격 변동 패턴
price_patterns:
  daily_cycle:
    # 시간대별 가격 배율
    "00-06": 0.95  # 새벽 할인
    "06-09": 1.05  # 아침 프리미엄
    "09-12": 1.10  # 오전 피크
    "12-15": 1.00  # 점심 보통
    "15-18": 1.15  # 오후 피크
    "18-21": 1.20  # 저녁 최고가
    "21-24": 1.02  # 밤 소폭 상승
    
  weekly_cycle:
    monday: 1.05
    tuesday: 1.10
    wednesday: 1.08
    thursday: 1.12
    friday: 1.15
    saturday: 0.95
    sunday: 0.90
    
  market_events:
    # 특별 이벤트 시뮬레이션
    high_demand: 
      probability: 0.05  # 5% 확률
      price_multiplier: 1.5
      duration_hours: [2, 6]
      
    network_congestion:
      probability: 0.03  # 3% 확률
      price_multiplier: 2.0
      duration_hours: [1, 3]
      
    maintenance:
      probability: 0.02  # 2% 확률
      availability_reduction: 0.5
      duration_hours: [4, 12]

# 공급업체 상태 시나리오
supplier_scenarios:
  normal_operation:
    probability: 0.85
    all_suppliers_available: true
    
  single_supplier_down:
    probability: 0.10
    affected_suppliers: 1
    
  high_demand_surge:
    probability: 0.03
    demand_multiplier: 3.0
    duration_hours: [1, 4]
    
  system_wide_issue:
    probability: 0.02
    all_suppliers_affected: true
    capacity_reduction: 0.7
    duration_hours: [2, 8]

# 에너지 주문 패턴
order_patterns:
  small_orders:
    energy_range: [1000, 10000]  # 1K-10K 에너지
    frequency: 60%
    
  medium_orders:
    energy_range: [10000, 100000]  # 10K-100K 에너지
    frequency: 30%
    
  large_orders:
    energy_range: [100000, 1000000]  # 100K-1M 에너지
    frequency: 8%
    
  bulk_orders:
    energy_range: [1000000, 10000000]  # 1M-10M 에너지
    frequency: 2%
